# Generated by Django 5.0.6 on 2026-08-20 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='kilometers',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje Actual'),
        ),
        migrations.CreateModel(
            name='StartUpChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha / Hora')),
                ('kilometers', models.PositiveIntegerField(verbose_name='Kilometraje')),
                ('control_type', models.CharField(choices=[('REGULAR', 'Regular'), ('PRE_TRIP', 'Previaje')], default='REGULAR', max_length=10, verbose_name='Tipo de Control')),
                ('oil_level', models.CharField(choices=[('BIEN', 'Bien'), ('REGULAR', 'Regular'), ('BAJO', 'Bajo')], max_length=10, verbose_name='Aceite')),
                ('oil_observations', models.TextField(blank=True, null=True, verbose_name='Obs. Aceite')),
                ('coolant_level', models.CharField(choices=[('BIEN', 'Bien'), ('REGULAR', 'Regular'), ('VACIO', 'Vacío')], max_length=10, verbose_name='Refrigerante')),
                ('coolant_observations', models.TextField(blank=True, null=True, verbose_name='Obs. Refrigerante')),
                ('tires_status', models.CharField(choices=[('BUENO', 'Bueno'), ('MALO', 'Malo')], max_length=10, verbose_name='Cubiertas')),
                ('tires_observations', models.TextField(blank=True, null=True, verbose_name='Obs. Cubiertas')),
                ('lights_status', models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('FALLA', 'Falla detectada')], max_length=10, verbose_name='Luces')),
                ('lights_observations', models.TextField(blank=True, null=True, verbose_name='Obs. Luces')),
                ('brakes_status', models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('FALLA', 'Falla detectada')], max_length=10, verbose_name='Frenos')),
                ('brakes_observations', models.TextField(blank=True, null=True, verbose_name='Obs. Frenos')),
                ('overall_status', models.CharField(blank=True, choices=[('SUITABLE', 'Apto para trabajar'), ('CAUTION', 'Operar con precaución'), ('UNSUITABLE', 'No apto para conducir')], max_length=15, verbose_name='Estado General')),
                ('reported_to', models.CharField(blank=True, max_length=150, null=True, verbose_name='Reportado a')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startup_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Operario')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_checklists', to='api.vehicle', verbose_name='Vehículo')),
            ],
        ),
    ]
