# Generated by Django 5.0.6 on 2026-08-20 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehicle_kilometers_startupchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('kilometers', models.PositiveIntegerField(verbose_name='Kilómetros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('engine_oil_level', models.CharField(choices=[('BIEN', 'Bien'), ('BAJO', 'Bajo'), ('EXCESO', 'Exceso')], max_length=10, verbose_name='Nivel de aceite')),
                ('engine_oil_condition', models.CharField(choices=[('NORMAL', 'Normal'), ('CONTAMINADO', 'Contaminado'), ('QUEMADO', 'Quemado')], max_length=15, verbose_name='Estado del aceite')),
                ('engine_oil_leaks', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Pérdidas de aceite')),
                ('engine_coolant_level', models.CharField(choices=[('BIEN', 'Bien'), ('BAJO', 'Bajo'), ('EXCESO', 'Exceso')], max_length=10, verbose_name='Nivel del refrigerante')),
                ('engine_coolant_condition', models.CharField(choices=[('BIEN', 'Bien'), ('CONTAMINADO', 'Contaminado'), ('OTRO', 'Otro')], max_length=15, verbose_name='Estado del refrigerante')),
                ('engine_coolant_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. refrigerante')),
                ('engine_temp', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTA', 'Alta')], max_length=10, verbose_name='Temperatura de trabajo')),
                ('engine_general_obs', models.TextField(blank=True, null=True, verbose_name='Observaciones motor')),
                ('trans_clutch', models.CharField(choices=[('BIEN', 'Bien'), ('DESGASTE', 'Desgaste')], max_length=10, verbose_name='Embrague')),
                ('trans_gearbox', models.CharField(choices=[('BIEN', 'Bien'), ('RUIDOS', 'Ruidos'), ('DURA', 'Dura')], max_length=10, verbose_name='Caja de cambios')),
                ('trans_leaks', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Pérdidas transmisión')),
                ('trans_leaks_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. pérdidas')),
                ('trans_general_obs', models.TextField(blank=True, null=True, verbose_name='Observaciones transmisión')),
                ('brakes_front_pads', models.CharField(choices=[('BIEN', 'Bien'), ('CAMBIAR', 'Cambiar')], max_length=10, verbose_name='Pastillas delanteras')),
                ('brakes_front_pads_wear_pct', models.PositiveIntegerField(blank=True, null=True, verbose_name='% Desgaste pastillas')),
                ('brakes_discs', models.CharField(choices=[('BIEN', 'Bien'), ('DESGASTE', 'Desgaste')], max_length=10, verbose_name='Discos')),
                ('brakes_discs_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. discos')),
                ('brakes_fluid_level', models.CharField(choices=[('BIEN', 'Bien'), ('BAJO', 'Bajo'), ('EXCESO', 'Exceso')], max_length=10, verbose_name='Nivel líquido de frenos')),
                ('brakes_fluid_state', models.CharField(choices=[('OK', 'OK'), ('CONTAMINADO', 'Contaminado')], max_length=15, verbose_name='Estado líquido de frenos')),
                ('brakes_fluid_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. líquido')),
                ('brakes_rear', models.CharField(choices=[('BIEN', 'Bien'), ('REGULAR', 'Regular')], max_length=10, verbose_name='Freno trasero (Cintas/Tambor)')),
                ('brakes_rear_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. freno trasero')),
                ('brakes_general_obs', models.TextField(blank=True, null=True, verbose_name='Observaciones generales frenos')),
                ('susp_shock_absorbers', models.CharField(choices=[('BIEN', 'Bien'), ('MALO', 'Malo')], max_length=10, verbose_name='Amortiguadores')),
                ('susp_shock_absorbers_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. amortiguadores')),
                ('susp_ball_joints', models.CharField(choices=[('BIEN', 'Bien'), ('MALO', 'Malo')], max_length=10, verbose_name='Rótulas')),
                ('susp_ball_joints_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. rótulas')),
                ('susp_bushings', models.CharField(choices=[('BIEN', 'Bien'), ('MALO', 'Malo')], max_length=10, verbose_name='Bujes de parrilla')),
                ('susp_bushings_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. bujes')),
                ('susp_tie_rod_ends', models.CharField(choices=[('BIEN', 'Bien'), ('MALO', 'Malo')], max_length=10, verbose_name='Extremos de dirección')),
                ('susp_tie_rod_ends_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. extremos')),
                ('susp_sway_bar', models.CharField(choices=[('BIEN', 'Bien'), ('MALO', 'Malo')], max_length=10, verbose_name='Barra estabilizadora')),
                ('susp_sway_bar_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. barra')),
                ('susp_general_obs', models.TextField(blank=True, null=True, verbose_name='Observaciones generales suspensión')),
                ('elec_battery', models.CharField(choices=[('BIEN', 'Bien'), ('PROBLEMA', 'Problema')], max_length=10, verbose_name='Batería')),
                ('elec_battery_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. batería')),
                ('elec_charging_system', models.CharField(choices=[('BIEN', 'Bien'), ('PROBLEMA', 'Problema')], max_length=10, verbose_name='Sistema de carga')),
                ('elec_charging_system_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. sistema de carga')),
                ('elec_lights', models.CharField(choices=[('BIEN', 'Bien'), ('PROBLEMA', 'Problema')], max_length=10, verbose_name='Luces (Altas/Bajas/Stop/Giro)')),
                ('elec_lights_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. luces')),
                ('belts_auxiliary', models.CharField(choices=[('BIEN', 'Bien'), ('CAMBIAR', 'Cambiar')], max_length=10, verbose_name='Correas auxiliares')),
                ('belts_auxiliary_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obs. correas auxiliares')),
                ('belts_distribution_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Distribución')),
                ('belts_water_pump_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bomba de agua')),
                ('belts_general_obs', models.TextField(blank=True, null=True, verbose_name='Observaciones generales correas')),
                ('tires_tread_depth', models.CharField(choices=[('BIEN', 'Bien'), ('LIMITE', 'Límite')], max_length=10, verbose_name='Profundidad del dibujo')),
                ('tires_tread_depth_mm', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Profundidad (mm)')),
                ('tires_pressure', models.CharField(choices=[('BIEN', 'Bien'), ('BAJO', 'Bajo')], max_length=10, verbose_name='Presión')),
                ('tires_pressure_psi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Presión (PSI)')),
                ('tires_obs', models.TextField(blank=True, null=True, verbose_name='Observaciones neumáticos')),
                ('diagnosis', models.CharField(choices=[('OPTIMO', 'Óptimo'), ('MANTENIMIENTO', 'Requiere mantenimiento'), ('REPARACION', 'Requiere reparación')], max_length=20, verbose_name='Diagnóstico general')),
                ('recommended_actions', models.TextField(blank=True, null=True, verbose_name='Acciones recomendadas')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='Mecánico')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='api.vehicle', verbose_name='Vehículo')),
            ],
        ),
    ]
